const database = {
    "sql": [
        {
            "setName": "Set 1",
            "question": "Create following tables with primary and foreign keys and solve the queries given below. Primary keys are underlined\nPerson (driver_id, name, address)\nCar (license, model, year)\nAccident (report_no, date_acc, location)\nOwns (driver_id, license)\nParticipated (driver_id, model, report_no, damage_amount)\n1) Insert 5 records into each table\n2) Display the Schema of each table.\n3) Display all records from the person table\n4) Set a Foreign key constraint from Participated.report_no to Accident.report_no.\n5) Add check constraints on Damage_amount that amt should not be negative.\n6) Write a query to make the name column in the Person table NOT NULL.\n7) Rename the Car table to Vehicle.\n8) Create a new table named new_person from existing person table and drop the table new_person.",
            "solution": "CREATE TABLE Person(\ndriver_id NUMBER PRIMARY KEY,\nname VARCHAR2(50),\naddress VARCHAR2(100)\n);\n\nCREATE TABLE Car(\nlicense VARCHAR2(20) PRIMARY KEY,\nmodel VARCHAR2(30),\nyear NUMBER(4)\n);\n\nCREATE TABLE Accident(\nreport_no NUMBER PRIMARY KEY,\ndate_acc DATE,\nlocation VARCHAR2(100)\n);\n\nCREATE TABLE Owns(\ndriver_id NUMBER,\nlicense VARCHAR2(20),\nPRIMARY KEY(driver_id,license),\nFOREIGN KEY(driver_id) REFERENCES Person(driver_id),\nFOREIGN KEY(license) REFERENCES Car(license)\n);\n\nCREATE TABLE Participated(\ndriver_id NUMBER,\nmodel VARCHAR2(30),\nreport_no NUMBER,\ndamage_amount NUMBER,\nPRIMARY KEY(driver_id,report_no)\n);\n\nINSERT INTO Person VALUES(1,'Amit','Pune');\nINSERT INTO Person VALUES(2,'Rohit','Mumbai');\nINSERT INTO Person VALUES(3,'Sneha','Nashik');\nINSERT INTO Person VALUES(4,'Priya','Nagpur');\nINSERT INTO Person VALUES(5,'Karan','Delhi');\n\nINSERT INTO Car VALUES('MH12AB1234','Honda',2020);\nINSERT INTO Car VALUES('MH14XY5678','Hyundai',2021);\nINSERT INTO Car VALUES('MH01CD3456','Toyota',2019);\nINSERT INTO Car VALUES('MH20EF7890','BMW',2022);\nINSERT INTO Car VALUES('MH15GH4321','Audi',2023);\n\nINSERT INTO Accident VALUES(101,TO_DATE('10-01-2025','DD-MM-YYYY'),'Pune');\nINSERT INTO Accident VALUES(102,TO_DATE('15-02-2025','DD-MM-YYYY'),'Mumbai');\nINSERT INTO Accident VALUES(103,TO_DATE('20-03-2025','DD-MM-YYYY'),'Nashik');\nINSERT INTO Accident VALUES(104,TO_DATE('25-04-2025','DD-MM-YYYY'),'Delhi');\nINSERT INTO Accident VALUES(105,TO_DATE('30-05-2025','DD-MM-YYYY'),'Nagpur');\n\nINSERT INTO Owns VALUES(1,'MH12AB1234');\nINSERT INTO Owns VALUES(2,'MH14XY5678');\nINSERT INTO Owns VALUES(3,'MH01CD3456');\nINSERT INTO Owns VALUES(4,'MH20EF7890');\nINSERT INTO Owns VALUES(5,'MH15GH4321');\n\nINSERT INTO Participated VALUES(1,'Honda',101,20000);\nINSERT INTO Participated VALUES(2,'Hyundai',102,15000);\nINSERT INTO Participated VALUES(3,'Toyota',103,10000);\nINSERT INTO Participated VALUES(4,'BMW',104,50000);\nINSERT INTO Participated VALUES(5,'Audi',105,30000);\n\nDESC Person;\nDESC Car;\nDESC Accident;\nDESC Owns;\nDESC Participated;\n\nSELECT * FROM Person;\n\nALTER TABLE Participated\nADD CONSTRAINT fk_report\nFOREIGN KEY(report_no)\nREFERENCES Accident(report_no);\n\nALTER TABLE Participated\nADD CONSTRAINT chk_damage\nCHECK(damage_amount >= 0);\n\nALTER TABLE Person\nMODIFY name VARCHAR2(50) NOT NULL;\n\nRENAME Car TO Vehicle;\n\nCREATE TABLE new_person AS\nSELECT * FROM Person;\n\nSELECT * FROM new_person;\n\nDROP TABLE new_person;"
        },
        {
            "setName": "Set 2",
            "question": "Create Customer and Account table and add rows shown below\n1) Show the cname, Acc_Type, amount information of customer who is having an saving account.\n2. Display the data using Natural, left and right join.\n3. Display the information of customers living in the same city as of 'pooja'.\n4. Display the information of account, having less amount than average amount throughout the bank.\n5. Display the C_id having maximum amount in account.\n6. Display the amount and acc_type of those customers whose amount is the minimum amount of that Acc_type.\n7. Display the amount of those accounts whose amount is higher than amount of any saving account amount.",
            "solution": "CREATE TABLE Customer(\nc_id NUMBER PRIMARY KEY,\ncname VARCHAR2(30),\ncity VARCHAR2(30)\n);\n\nCREATE TABLE Account(\nacc_no NUMBER PRIMARY KEY,\nc_id NUMBER,\nacc_type VARCHAR2(20),\namount NUMBER,\nFOREIGN KEY(c_id) REFERENCES Customer(c_id)\n);\n\nINSERT INTO Customer VALUES(1,'Pooja','Pune');\nINSERT INTO Customer VALUES(2,'Amit','Mumbai');\nINSERT INTO Customer VALUES(3,'Rohit','Pune');\nINSERT INTO Customer VALUES(4,'Sneha','Delhi');\nINSERT INTO Customer VALUES(5,'Karan','Mumbai');\n\nINSERT INTO Account VALUES(101,1,'Saving',50000);\nINSERT INTO Account VALUES(102,2,'Current',70000);\nINSERT INTO Account VALUES(103,3,'Saving',30000);\nINSERT INTO Account VALUES(104,4,'Current',90000);\nINSERT INTO Account VALUES(105,5,'Saving',20000);\n\nSELECT c.cname,a.acc_type,a.amount\nFROM Customer c\nJOIN Account a\nON c.c_id=a.c_id\nWHERE a.acc_type='Saving';\n\nSELECT * FROM Customer NATURAL JOIN Account;\n\nSELECT *\nFROM Customer c\nLEFT JOIN Account a\nON c.c_id=a.c_id;\n\nSELECT *\nFROM Customer c\nRIGHT JOIN Account a\nON c.c_id=a.c_id;\n\nSELECT *\nFROM Customer\nWHERE city=(\nSELECT city\nFROM Customer\nWHERE cname='Pooja'\n);\n\nSELECT *\nFROM Account\nWHERE amount<(\nSELECT AVG(amount)\nFROM Account\n);\n\nSELECT c_id\nFROM Account\nWHERE amount=(\nSELECT MAX(amount)\nFROM Account\n);\n\nSELECT amount,acc_type\nFROM Account a\nWHERE amount=(\nSELECT MIN(amount)\nFROM Account\nWHERE acc_type=a.acc_type\n);\n\nSELECT amount\nFROM Account\nWHERE amount>ANY(\nSELECT amount\nFROM Account\nWHERE acc_type='Saving'\n);"
        },
        {
            "setName": "Set 3",
            "question": "Create Employee and Department table by identifying Primary key and foreign keys and solve the following queries\nEmployee (emp_id, emp_name, city, salary, department)\nDepartment (dept_id, dept_name, location)\n1. Display schema of each table.\n2. Insert 10 records in each table\n3. Insert a new department into the Department table.\n4. Insert an employee record without specifying the salary column.\n5. Update the salary of all employees by adding 20% increment.\n6. Display employee name and annual salary of employees whose names having the second letter e.\n7. Update the city to 'Pune' for employees working in the 'IT' department.",
            "solution": "CREATE TABLE Department(\ndept_id NUMBER PRIMARY KEY,\ndept_name VARCHAR2(30),\nlocation VARCHAR2(30)\n);\n\nCREATE TABLE Employee(\nemp_id NUMBER PRIMARY KEY,\nemp_name VARCHAR2(30),\ncity VARCHAR2(30),\nsalary NUMBER,\ndepartment NUMBER,\nFOREIGN KEY(department) REFERENCES Department(dept_id)\n);\n\nINSERT INTO Department VALUES(1,'IT','Pune');\nINSERT INTO Department VALUES(2,'HR','Mumbai');\nINSERT INTO Department VALUES(3,'Sales','Delhi');\nINSERT INTO Department VALUES(4,'Finance','Chennai');\nINSERT INTO Department VALUES(5,'Admin','Nagpur');\n\nINSERT INTO Employee VALUES(101,'Amit','Mumbai',50000,1);\nINSERT INTO Employee VALUES(102,'Rohit','Pune',60000,1);\nINSERT INTO Employee VALUES(103,'Sneha','Delhi',45000,2);\nINSERT INTO Employee VALUES(104,'Karan','Nagpur',70000,3);\nINSERT INTO Employee VALUES(105,'Priya','Mumbai',80000,4);\nINSERT INTO Employee VALUES(106,'Neha','Pune',55000,5);\nINSERT INTO Employee VALUES(107,'Ajay','Delhi',40000,2);\nINSERT INTO Employee VALUES(108,'Tejas','Mumbai',75000,1);\nINSERT INTO Employee VALUES(109,'Seema','Nagpur',65000,3);\nINSERT INTO Employee VALUES(110,'Komal','Pune',72000,4);\n\nDESC Employee;\nDESC Department;\n\nSELECT * FROM Employee;\nSELECT * FROM Department;\n\nINSERT INTO Department\nVALUES(6,'Testing','Hyderabad');\n\nINSERT INTO Employee(emp_id,emp_name,city,department)\nVALUES(111,'Raj','Pune',1);\n\nUPDATE Employee\nSET salary=salary+(salary*0.20);\n\nSELECT emp_name,salary*12 AS annual_salary\nFROM Employee\nWHERE emp_name LIKE '_e%';\n\nUPDATE Employee\nSET city='Pune'\nWHERE department=(\nSELECT dept_id\nFROM Department\nWHERE dept_name='IT'\n);"
        },
        {
            "setName": "Set 4",
            "question": "Create Employee and Department table by identifying Primary key and foreign keys\nEmployee (emp_id, emp_name, city, salary, department)\nDepartment (dept_id, dept_name, location)\n1. Display schema of each table.\n2. Insert 10 records in each table\n3. Update the city to 'Pune' for employees working in the 'IT' department.\n4. Delete employee records whose salary is greater than 100000.\n5. Display employee name and salary after deducting 5% tax.\n6. Display employees who do not live in 'Mumbai' and whose names start with a.\n7. Display employees who belong to 'IT' department and have salary greater than 50000.",
            "solution": "CREATE TABLE Department1(\ndept_id NUMBER PRIMARY KEY,\ndept_name VARCHAR2(30),\nlocation VARCHAR2(30)\n);\n\nCREATE TABLE Employee1(\nemp_id NUMBER PRIMARY KEY,\nemp_name VARCHAR2(30),\ncity VARCHAR2(30),\nsalary NUMBER,\ndepartment NUMBER,\nFOREIGN KEY(department) REFERENCES Department1(dept_id)\n);\n\nINSERT INTO Department1 VALUES(1,'IT','Pune');\nINSERT INTO Department1 VALUES(2,'HR','Mumbai');\nINSERT INTO Department1 VALUES(3,'Sales','Delhi');\nINSERT INTO Department1 VALUES(4,'Finance','Chennai');\nINSERT INTO Department1 VALUES(5,'Admin','Nagpur');\n\nINSERT INTO Employee1 VALUES(101,'Amit','Mumbai',50000,1);\nINSERT INTO Employee1 VALUES(102,'Rohit','Pune',60000,1);\nINSERT INTO Employee1 VALUES(103,'Sneha','Delhi',45000,2);\nINSERT INTO Employee1 VALUES(104,'Karan','Nagpur',120000,3);\nINSERT INTO Employee1 VALUES(105,'Priya','Mumbai',80000,4);\nINSERT INTO Employee1 VALUES(106,'Neha','Pune',55000,5);\nINSERT INTO Employee1 VALUES(107,'Ajay','Delhi',40000,2);\nINSERT INTO Employee1 VALUES(108,'Tejas','Mumbai',75000,1);\nINSERT INTO Employee1 VALUES(109,'Seema','Nagpur',65000,3);\nINSERT INTO Employee1 VALUES(110,'Komal','Pune',72000,4);\n\nDESC Employee1;\nDESC Department1;\n\nUPDATE Employee1\nSET city='Pune'\nWHERE department=(\nSELECT dept_id\nFROM Department1\nWHERE dept_name='IT'\n);\n\nDELETE FROM Employee1\nWHERE salary>100000;\n\nSELECT emp_name,salary-(salary*0.05) AS salary_after_tax\nFROM Employee1;\n\nSELECT *\nFROM Employee1\nWHERE city<>'Mumbai'\nAND emp_name LIKE 'A%';\n\nSELECT *\nFROM Employee1\nWHERE department=(\nSELECT dept_id\nFROM Department1\nWHERE dept_name='IT'\n)\nAND salary>50000;"
        },
        {
            "setName": "Set 5",
            "question": "1. Create a new user named with Class_div_rollno.\n2. Grant SELECT permission on the Employee table to a user named Class_div_rollno\n3. Grant INSERT and UPDATE permissions on the Employee table to Class_div_rollno\n4. Revoke UPDATE permission from user1.\n5. Create a role named manager_role.\n6. Grant SELECT and DELETE privileges on Employee table to manager_role.\n7. Revoke the role manager_role from user2",
            "solution": "CREATE USER class_div_rollno IDENTIFIED BY pass123;\n\nGRANT SELECT ON Employee TO class_div_rollno;\n\nGRANT INSERT,UPDATE ON Employee TO class_div_rollno;\n\nREVOKE UPDATE ON Employee FROM user1;\n\nCREATE ROLE manager_role;\n\nGRANT SELECT,DELETE ON Employee TO manager_role;\n\nREVOKE manager_role FROM user2;"
        },
        {
            "setName": "Set 6",
            "question": "Create the tables below and solve the following queries.\nEmployees (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)\nDepartments (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID)\n1. Create EmpTest from Emp table by copying structure and data.\n2. Add a new row into the EmpTest table for Empno,Ename,Sal columns. In Ename should have the Current User.\n3. Update EmpTest by increasing the Salary of Vaishali by 15%. Confirm your changes.\n4. Increase all the employees salary by 10% in EmpTest table who are working in PUNE\n5. Delete all the Comm data from EmpTest Table.\n6. Delete all the employees in deptno 10 and do not issue a Commit.\n7. Issue a Rollback and reflect changes.",
            "solution": "CREATE TABLE Employees(\nemployee_id NUMBER(6) PRIMARY KEY,\nfirst_name VARCHAR2(20),\nlast_name VARCHAR2(25) NOT NULL,\nemail VARCHAR2(25) NOT NULL,\nphone_number VARCHAR2(20),\nhire_date DATE NOT NULL,\njob_id VARCHAR2(10) NOT NULL,\nsalary NUMBER(8,2),\ncommission_pct NUMBER(2,2),\nmanager_id NUMBER(6),\ndepartment_id NUMBER(4)\n);\n\nCREATE TABLE Departments(\ndepartment_id NUMBER(4) PRIMARY KEY,\ndepartment_name VARCHAR2(30) NOT NULL,\nmanager_id NUMBER(6),\nlocation_id NUMBER(4)\n);\n\nINSERT INTO Departments VALUES(10,'IT',101,1);\nINSERT INTO Departments VALUES(20,'HR',102,2);\nINSERT INTO Departments VALUES(30,'Sales',103,3);\n\nINSERT INTO Employees VALUES(101,'Vaishali','Patil','v@gmail.com','9999999999',SYSDATE,'MGR',50000,0.1,201,10);\nINSERT INTO Employees VALUES(102,'Amit','Shah','a@gmail.com','8888888888',SYSDATE,'HR',40000,0.2,202,20);\nINSERT INTO Employees VALUES(103,'Rohit','Kale','r@gmail.com','7777777777',SYSDATE,'SALE',35000,0.1,203,30);\n\nCREATE TABLE EmpTest AS\nSELECT * FROM Employees;\n\nINSERT INTO EmpTest(employee_id,first_name,salary)\nVALUES(104,USER,45000);\n\nUPDATE EmpTest\nSET salary=salary+(salary*0.15)\nWHERE first_name='Vaishali';\n\nSELECT * FROM EmpTest\nWHERE first_name='Vaishali';\n\nUPDATE EmpTest\nSET salary=salary+(salary*0.10)\nWHERE department_id IN(\nSELECT department_id\nFROM Departments\nWHERE department_name='IT'\n);\n\nUPDATE EmpTest\nSET commission_pct=NULL;\n\nDELETE FROM EmpTest\nWHERE department_id=10;\n\nROLLBACK;\n\nSELECT * FROM EmpTest;"
        },
        {
            "setName": "Set 7",
            "question": "Create the table below and solve the following queries.\nEmployees (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)\n1. Start a transaction and insert a new employee record. Commit the transaction.\n2. Start a transaction, update employee salary, and rollback the transaction.\n3. Start a transaction, create a savepoint named SP1, update salary, and rollback to SP1.\n4. Demonstrate the use of multiple savepoints within a single transaction.\n5. Start a transaction, delete an employee record, and commit the changes.",
            "solution": "CREATE TABLE Employees1(\nemployee_id NUMBER(6) PRIMARY KEY,\nfirst_name VARCHAR2(20),\nlast_name VARCHAR2(25) NOT NULL,\nemail VARCHAR2(25) NOT NULL,\nphone_number VARCHAR2(20),\nhire_date DATE NOT NULL,\njob_id VARCHAR2(10) NOT NULL,\nsalary NUMBER(8,2),\ncommission_pct NUMBER(2,2),\nmanager_id NUMBER(6),\ndepartment_id NUMBER(4)\n);\n\nINSERT INTO Employees1 VALUES(101,'Amit','Patil','a@gmail.com','9999999999',SYSDATE,'MGR',50000,0.1,201,10);\nINSERT INTO Employees1 VALUES(102,'Rohit','Kale','r@gmail.com','8888888888',SYSDATE,'HR',40000,0.2,202,20);\nINSERT INTO Employees1 VALUES(103,'Sneha','Shah','s@gmail.com','7777777777',SYSDATE,'SALE',35000,0.1,203,30);\n\nINSERT INTO Employees1\nVALUES(104,'Karan','Patil','k@gmail.com','6666666666',SYSDATE,'DEV',45000,0.1,204,40);\n\nCOMMIT;\n\nUPDATE Employees1\nSET salary=salary+5000\nWHERE employee_id=101;\n\nROLLBACK;\n\nSAVEPOINT SP1;\n\nUPDATE Employees1\nSET salary=salary+2000\nWHERE employee_id=102;\n\nROLLBACK TO SP1;\n\nSAVEPOINT SP2;\n\nUPDATE Employees1\nSET salary=salary+1000\nWHERE employee_id=101;\n\nSAVEPOINT SP3;\n\nUPDATE Employees1\nSET salary=salary+3000\nWHERE employee_id=103;\n\nROLLBACK TO SP2;\n\nDELETE FROM Employees1\nWHERE employee_id=104;\n\nCOMMIT;\n\nSELECT * FROM Employees1;"
        },
        {
            "setName": "Set 8",
            "question": "Create the employee table with all constraints.\n1. Find the highest, lowest, sum and average salary of all employees. Label the columns.\n2. write a query to display the number of people with the same job.\n3. Determine the number of managers without listing them. Label the column number of Managers\n4. Find the difference between the highest and lowest salaries. Label the column DIFFERENCE.\n5. Create a report to display the manager number and the salary of the lowest-paid employee for that manager.",
            "solution": "CREATE TABLE Employee2(\nemployee_id NUMBER(6) PRIMARY KEY,\nfirst_name VARCHAR2(20),\nlast_name VARCHAR2(25) NOT NULL,\nemail VARCHAR2(25) NOT NULL,\nphone_number VARCHAR2(20),\nhire_date DATE NOT NULL,\njob_id VARCHAR2(10) NOT NULL,\nsalary NUMBER(8,2),\ncommission_pct NUMBER(2,2),\nmanager_id NUMBER(6),\ndepartment_id NUMBER(4)\n);\n\nINSERT INTO Employee2 VALUES(101,'Amit','Patil','a@gmail.com','9999999999',SYSDATE,'MGR',50000,0.1,201,10);\nINSERT INTO Employee2 VALUES(102,'Rohit','Kale','r@gmail.com','8888888888',SYSDATE,'HR',40000,0.2,202,20);\nINSERT INTO Employee2 VALUES(103,'Sneha','Shah','s@gmail.com','7777777777',SYSDATE,'SALE',35000,0.1,203,30);\nINSERT INTO Employee2 VALUES(104,'Karan','Patil','k@gmail.com','6666666666',SYSDATE,'DEV',45000,0.1,204,40);\nINSERT INTO Employee2 VALUES(105,'Priya','More','p@gmail.com','5555555555',SYSDATE,'HR',55000,0.2,202,20);\n\nSELECT \nMAX(salary) AS Highest_Salary,\nMIN(salary) AS Lowest_Salary,\nSUM(salary) AS Total_Salary,\nAVG(salary) AS Average_Salary\nFROM Employee2;\n\nSELECT \njob_id,\nCOUNT(*) AS Number_Of_People\nFROM Employee2\nGROUP BY job_id;\n\nSELECT \nCOUNT(DISTINCT manager_id) AS Number_Of_Managers\nFROM Employee2;\n\nSELECT \nMAX(salary)-MIN(salary) AS DIFFERENCE\nFROM Employee2;\n\nSELECT \nmanager_id,\nMIN(salary) AS Lowest_Paid_Salary\nFROM Employee2\nGROUP BY manager_id;"
        },
        {
            "setName": "Set 9",
            "question": "Create the employee table with all constraints and solve the following queries.\nEmployee (emp_id, emp_name, department, city, salary)\n1. Display department-wise total salary of employees.\n2. Display department-wise average salary.\n3. City-wise employee count greater than 3\n4. Department-wise maximum salary above 60,000\n5. Display department and city-wise total salary.\n6. Display departments having more than one employee.\n7. Display city-wise employee count in descending order.",
            "solution": "CREATE TABLE Employee3(\nemp_id NUMBER PRIMARY KEY,\nemp_name VARCHAR2(30),\ndepartment VARCHAR2(30),\ncity VARCHAR2(30),\nsalary NUMBER\n);\n\nINSERT INTO Employee3 VALUES(101,'Amit','IT','Pune',50000);\nINSERT INTO Employee3 VALUES(102,'Rohit','IT','Mumbai',60000);\nINSERT INTO Employee3 VALUES(103,'Sneha','HR','Pune',45000);\nINSERT INTO Employee3 VALUES(104,'Karan','Sales','Delhi',70000);\nINSERT INTO Employee3 VALUES(105,'Priya','Finance','Mumbai',80000);\nINSERT INTO Employee3 VALUES(106,'Neha','IT','Pune',55000);\nINSERT INTO Employee3 VALUES(107,'Ajay','HR','Delhi',40000);\nINSERT INTO Employee3 VALUES(108,'Tejas','IT','Mumbai',75000);\nINSERT INTO Employee3 VALUES(109,'Seema','Sales','Nagpur',65000);\nINSERT INTO Employee3 VALUES(110,'Komal','Finance','Pune',72000);\n\nSELECT department,SUM(salary) AS Total_Salary\nFROM Employee3\nGROUP BY department;\n\nSELECT department,AVG(salary) AS Average_Salary\nFROM Employee3\nGROUP BY department;\n\nSELECT city,COUNT(*) AS Employee_Count\nFROM Employee3\nGROUP BY city\nHAVING COUNT(*)>3;\n\nSELECT department,MAX(salary) AS Maximum_Salary\nFROM Employee3\nGROUP BY department\nHAVING MAX(salary)>60000;\n\nSELECT department,city,SUM(salary) AS Total_Salary\nFROM Employee3\nGROUP BY department,city;\n\nSELECT department,COUNT(*) AS Employee_Count\nFROM Employee3\nGROUP BY department\nHAVING COUNT(*)>1;\n\nSELECT city,COUNT(*) AS Employee_Count\nFROM Employee3\nGROUP BY city\nORDER BY COUNT(*) DESC;"
        },
        {
            "setName": "Set 10",
            "question": "Create the employee table with all constraints and solve the following queries.\nEmployee (emp_id, emp_name, department, city, salary)\n1. Department-wise total salary greater than 2,00,000\n2. Department-wise average salary more than 40,000\n3. Display city-wise number of employees.\n4. Display department-wise maximum salary.\n5. Display city-wise average salary.\n6. Display department-wise employee count where the number of employees is more than 3.\n7. Display city-wise employee count in ascending order.",
            "solution": "CREATE TABLE Employee4(\nemp_id NUMBER PRIMARY KEY,\nemp_name VARCHAR2(30),\ndepartment VARCHAR2(30),\ncity VARCHAR2(30),\nsalary NUMBER\n);\n\nINSERT INTO Employee4 VALUES(101,'Amit','IT','Pune',50000);\nINSERT INTO Employee4 VALUES(102,'Rohit','IT','Mumbai',60000);\nINSERT INTO Employee4 VALUES(103,'Sneha','HR','Pune',45000);\nINSERT INTO Employee4 VALUES(104,'Karan','Sales','Delhi',70000);\nINSERT INTO Employee4 VALUES(105,'Priya','Finance','Mumbai',80000);\nINSERT INTO Employee4 VALUES(106,'Neha','IT','Pune',55000);\nINSERT INTO Employee4 VALUES(107,'Ajay','HR','Delhi',40000);\nINSERT INTO Employee4 VALUES(108,'Tejas','IT','Mumbai',75000);\nINSERT INTO Employee4 VALUES(109,'Seema','Sales','Nagpur',65000);\nINSERT INTO Employee4 VALUES(110,'Komal','Finance','Pune',72000);\n\nSELECT department,SUM(salary) AS Total_Salary\nFROM Employee4\nGROUP BY department\nHAVING SUM(salary)>200000;\n\nSELECT department,AVG(salary) AS Average_Salary\nFROM Employee4\nGROUP BY department\nHAVING AVG(salary)>40000;\n\nSELECT city,COUNT(*) AS Number_Of_Employees\nFROM Employee4\nGROUP BY city;\n\nSELECT department,MAX(salary) AS Maximum_Salary\nFROM Employee4\nGROUP BY department;\n\nSELECT city,AVG(salary) AS Average_Salary\nFROM Employee4\nGROUP BY city;\n\nSELECT department,COUNT(*) AS Employee_Count\nFROM Employee4\nGROUP BY department\nHAVING COUNT(*)>3;\n\nSELECT city,COUNT(*) AS Employee_Count\nFROM Employee4\nGROUP BY city\nORDER BY COUNT(*) ASC;"
        },
        {
            "setName": "Set 11",
            "question": "1. Create a table dept1 as below with following columns:\nDEPTNO integer pk, dname varchar2(30) not null, loc varchar2(30) not null\n2.Add column mgr as number in the dept table.\n3. Create table empl with following columns\nempno integer ,ename varchar2(20) ,sal number(10,2) ,deptno number\n4. Add constraints on empl table\nEmpno-primary key, Ename-not null, Check sal>10000, Deptno as foreign key\n5.Create table dept11,emp11 from dept1,empl\n6.Add a new column address varchar2(30) in the empl table\n7.Rename sal column in empl table to salary\n8.Display constraints names and verify the names for the empl",
            "solution": "CREATE TABLE dept1(\ndeptno NUMBER PRIMARY KEY,\ndname VARCHAR2(30) NOT NULL,\nloc VARCHAR2(30) NOT NULL\n);\n\nALTER TABLE dept1\nADD mgr NUMBER;\n\nCREATE TABLE empl(\nempno NUMBER,\nename VARCHAR2(20),\nsal NUMBER(10,2),\ndeptno NUMBER\n);\n\nALTER TABLE empl\nADD CONSTRAINT pk_emp PRIMARY KEY(empno);\n\nALTER TABLE empl\nMODIFY ename VARCHAR2(20) NOT NULL;\n\nALTER TABLE empl\nADD CONSTRAINT chk_sal CHECK(sal>10000);\n\nALTER TABLE empl\nADD CONSTRAINT fk_dept\nFOREIGN KEY(deptno)\nREFERENCES dept1(deptno);\n\nCREATE TABLE dept11 AS\nSELECT * FROM dept1;\n\nCREATE TABLE emp11 AS\nSELECT * FROM empl;\n\nALTER TABLE empl\nADD address VARCHAR2(30);\n\nALTER TABLE empl\nRENAME COLUMN sal TO salary;\n\nSELECT constraint_name,constraint_type\nFROM user_constraints\nWHERE table_name='EMPL';"
        },
        {
            "setName": "Set 12",
            "question": "1.Write a query for the HR department to produce the addresses of all the departments. Use the EMP and DEPT tables. Show the EMPNO, ENAME,SAL,DNAME and LOC in the output. Use a NATURAL JOIN to produce the results.\n2.The HR department needs a report of all employees. Write a query to display the JOB, MGR, SAL,COMM,DNAME of employees whose JOB is SALESMAN.\n3.The HR department needs a report of employees in LOC DALLAS. Display the ENAME,job, DEPTNO and DNAME for all employees who work in DALLAS.\n4.Modify the previous Query to diaplay all employees including King,who has no manager.Order the results by the employee number.",
            "solution": "CREATE TABLE Departments12(\ndepartment_id NUMBER(4) PRIMARY KEY,\ndepartment_name VARCHAR2(30) NOT NULL,\nmanager_id NUMBER(6),\nlocation_id NUMBER(4)\n);\n\nCREATE TABLE Employees12(\nemployee_id NUMBER(6) PRIMARY KEY,\nfirst_name VARCHAR2(20),\nlast_name VARCHAR2(25) NOT NULL,\nemail VARCHAR2(25) NOT NULL,\nphone_number VARCHAR2(20),\nhire_date DATE NOT NULL,\njob_id VARCHAR2(10) NOT NULL,\nsalary NUMBER(8,2),\ncommission_pct NUMBER(2,2),\nmanager_id NUMBER(6),\ndepartment_id NUMBER(4),\nFOREIGN KEY(department_id)\nREFERENCES Departments12(department_id)\n);\n\nINSERT INTO Departments12 VALUES(10,'Sales',201,101);\nINSERT INTO Departments12 VALUES(20,'HR',202,102);\nINSERT INTO Departments12 VALUES(30,'IT',203,103);\n\nINSERT INTO Employees12 VALUES(101,'Amit','Patil','a@gmail.com','9999999999',SYSDATE,'SALESMAN',50000,0.1,201,10);\nINSERT INTO Employees12 VALUES(102,'Rohit','Kale','r@gmail.com','8888888888',SYSDATE,'HR',40000,0.2,202,20);\nINSERT INTO Employees12 VALUES(103,'Sneha','Shah','s@gmail.com','7777777777',SYSDATE,'DEV',60000,0.1,NULL,30);\n\nSELECT employee_id,first_name,salary,department_name,location_id\nFROM Employees12\nNATURAL JOIN Departments12;\n\nSELECT job_id,manager_id,salary,commission_pct,department_name\nFROM Employees12 e\nJOIN Departments12 d\nON e.department_id=d.department_id\nWHERE job_id='SALESMAN';\n\nSELECT first_name,job_id,department_id,department_name\nFROM Employees12 e\nJOIN Departments12 d\nON e.department_id=d.department_id\nWHERE location_id=101;\n\nSELECT employee_id,first_name,job_id,department_name\nFROM Employees12 e\nLEFT JOIN Departments12 d\nON e.department_id=d.department_id\nORDER BY employee_id;"
        },
        {
            "setName": "Set 13",
            "question": "1.The Hr department needs a report on job grades and salaries.To familiarize yourself with the SALGRADE table, first show the structure of the SALgrade table. Then create a query that displays the name,job,department name ,salary and grade for all employees.\n2.Display the ENAME,SAL,MGR,DNAME of employees whose salary is more than 2000.Use the ON clause.\n3.Display the EMPNO,ENAME,JOB,DEPTNO,DNAME,LOC of employees.Use left outer join.\n4.Display the Ename, Dname of employees.Use right outer join.\n5.Display the EMPNO,DNAME,LOC of employees.Use full outer join.",
            "solution": "CREATE TABLE Departments13(\ndepartment_id NUMBER(4) PRIMARY KEY,\ndepartment_name VARCHAR2(30),\nmanager_id NUMBER(6),\nlocation_id NUMBER(4)\n);\n\nCREATE TABLE Employees13(\nemployee_id NUMBER(6) PRIMARY KEY,\nfirst_name VARCHAR2(20),\njob_id VARCHAR2(20),\nsalary NUMBER(8,2),\nmanager_id NUMBER(6),\ndepartment_id NUMBER(4),\nFOREIGN KEY(department_id)\nREFERENCES Departments13(department_id)\n);\n\nCREATE TABLE Salgrade(\ngrade NUMBER,\nlosal NUMBER,\nhisal NUMBER\n);\n\nINSERT INTO Departments13 VALUES(10,'Sales',201,101);\nINSERT INTO Departments13 VALUES(20,'HR',202,102);\nINSERT INTO Departments13 VALUES(30,'IT',203,103);\n\nINSERT INTO Employees13 VALUES(101,'Amit','MANAGER',5000,201,10);\nINSERT INTO Employees13 VALUES(102,'Rohit','CLERK',2500,202,20);\nINSERT INTO Employees13 VALUES(103,'Sneha','DEV',4000,203,30);\n\nINSERT INTO Salgrade VALUES(1,1000,2000);\nINSERT INTO Salgrade VALUES(2,2001,3000);\nINSERT INTO Salgrade VALUES(3,3001,4000);\nINSERT INTO Salgrade VALUES(4,4001,5000);\n\nDESC Salgrade;\n\nSELECT first_name,job_id,department_name,salary,grade\nFROM Employees13 e\nJOIN Departments13 d\nON e.department_id=d.department_id\nJOIN Salgrade s\nON e.salary BETWEEN s.losal AND s.hisal;\n\nSELECT first_name,salary,manager_id,department_name\nFROM Employees13 e\nJOIN Departments13 d\nON e.department_id=d.department_id\nWHERE salary>2000;\n\nSELECT employee_id,first_name,job_id,e.department_id,department_name,location_id\nFROM Employees13 e\nLEFT OUTER JOIN Departments13 d\nON e.department_id=d.department_id;\n\nSELECT first_name,department_name\nFROM Employees13 e\nRIGHT OUTER JOIN Departments13 d\nON e.department_id=d.department_id;\n\nSELECT employee_id,department_name,location_id\nFROM Employees13 e\nFULL OUTER JOIN Departments13 d\nON e.department_id=d.department_id;"
        },
        {
            "setName": "Set 14",
            "question": "1.Write a query to display the JOB,MGR,SAL,COMM,DNAME of employees whose JOB is SALESMAN.\n2.The HR department needs a report of employees in Pune.Display the ENAME,job,DEPTNO and DNAME for all employees who work in Pune.\n3.Display the Ename,Dname of all the employees,Also display those department name which do not have any employees working\n4.Display the Ename,Dname of all the employees,Also display those departemnt name which do not have any employees working\n5.Display the EMPNO,ENAME,LOC of those employees who are working as CLERK",
            "solution": "CREATE TABLE Departments14(\ndepartment_id NUMBER(4) PRIMARY KEY,\ndepartment_name VARCHAR2(30),\nmanager_id NUMBER(6),\nlocation_id NUMBER(4)\n);\n\nCREATE TABLE Employees14(\nemployee_id NUMBER(6) PRIMARY KEY,\nfirst_name VARCHAR2(20),\njob_id VARCHAR2(20),\nsalary NUMBER(8,2),\ncommission_pct NUMBER(2,2),\nmanager_id NUMBER(6),\ndepartment_id NUMBER(4),\ncity VARCHAR2(30),\nFOREIGN KEY(department_id)\nREFERENCES Departments14(department_id)\n);\n\nINSERT INTO Departments14 VALUES(10,'Sales',201,101);\nINSERT INTO Departments14 VALUES(20,'HR',202,102);\nINSERT INTO Departments14 VALUES(30,'IT',203,103);\n\nINSERT INTO Employees14 VALUES(101,'Amit','SALESMAN',50000,0.1,201,10,'Pune');\nINSERT INTO Employees14 VALUES(102,'Rohit','CLERK',25000,0.2,202,20,'Mumbai');\nINSERT INTO Employees14 VALUES(103,'Sneha','DEV',60000,0.1,203,30,'Pune');\n\nSELECT job_id,manager_id,salary,commission_pct,department_name\nFROM Employees14 e\nJOIN Departments14 d\nON e.department_id=d.department_id\nWHERE job_id='SALESMAN';\n\nSELECT first_name,job_id,department_id,department_name\nFROM Employees14 e\nJOIN Departments14 d\nON e.department_id=d.department_id\nWHERE city='Pune';\n\nSELECT first_name,department_name\nFROM Employees14 e\nRIGHT OUTER JOIN Departments14 d\nON e.department_id=d.department_id;\n\nSELECT first_name,department_name\nFROM Employees14 e\nFULL OUTER JOIN Departments14 d\nON e.department_id=d.department_id;\n\nSELECT employee_id,first_name,location_id\nFROM Employees14 e\nJOIN Departments14 d\nON e.department_id=d.department_id\nWHERE job_id='CLERK';"
        },
        {
            "setName": "Set 20",
            "question": "Create following tables with primary and foreign key and solve the queries given below\nstudent(S_ID,name,dept_name,tot_cred)\ninstructor(T_ID,name,dept_name,salary)\ncourse(course_id,title,dept_name,credits)\ni. Find the average salary of instructor in those departments where the average salary is more than Rs. 42000/-.\nii. Increase the salary of each instructor in the computer department by 10%.\niii. Find the names of instructors whose names are neither 'Amol' nor 'Amit'.\niv. Find the names of student which contains 'am' as its substring.\nv. Find the name of students from computer department that \"DBMS\" courses they take.",
            "solution": "CREATE TABLE student(\ns_id NUMBER PRIMARY KEY,\nname VARCHAR2(30),\ndept_name VARCHAR2(30),\ntot_cred NUMBER\n);\n\nCREATE TABLE instructor(\nt_id NUMBER PRIMARY KEY,\nname VARCHAR2(30),\ndept_name VARCHAR2(30),\nsalary NUMBER\n);\n\nCREATE TABLE course(\ncourse_id NUMBER PRIMARY KEY,\ntitle VARCHAR2(30),\ndept_name VARCHAR2(30),\ncredits NUMBER\n);\n\nINSERT INTO student VALUES(1,'Amit','Computer',25);\nINSERT INTO student VALUES(2,'Rohit','Mechanical',20);\nINSERT INTO student VALUES(3,'Sneha','Computer',30);\nINSERT INTO student VALUES(4,'Priya','Civil',15);\nINSERT INTO student VALUES(5,'Karan','Computer',28);\n\nINSERT INTO instructor VALUES(101,'Amol','Computer',50000);\nINSERT INTO instructor VALUES(102,'Amit','Mechanical',40000);\nINSERT INTO instructor VALUES(103,'Neha','Computer',60000);\nINSERT INTO instructor VALUES(104,'Seema','Civil',35000);\nINSERT INTO instructor VALUES(105,'Tejas','Computer',70000);\n\nINSERT INTO course VALUES(1,'DBMS','Computer',4);\nINSERT INTO course VALUES(2,'TOC','Computer',3);\nINSERT INTO course VALUES(3,'Thermo','Mechanical',4);\nINSERT INTO course VALUES(4,'Survey','Civil',3);\nINSERT INTO course VALUES(5,'OS','Computer',4);\n\nSELECT dept_name,AVG(salary) AS Average_Salary\nFROM instructor\nGROUP BY dept_name\nHAVING AVG(salary)>42000;\n\nUPDATE instructor\nSET salary=salary+(salary*0.10)\nWHERE dept_name='Computer';\n\nSELECT name\nFROM instructor\nWHERE name NOT IN('Amol','Amit');\n\nSELECT name\nFROM student\nWHERE name LIKE '%am%';\n\nSELECT s.name\nFROM student s\nJOIN course c\nON s.dept_name=c.dept_name\nWHERE s.dept_name='Computer'\nAND c.title='DBMS';"
        },
        {
            "setName": "Set 23",
            "question": "Create below tables, insert 5 records each and solve the following queries\nEmployees (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)\nDepartments (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID)\n1. List employees whose salary is greater than the salary of ALLEN.\n2. Find employees whose job is the same as that of MARTIN.\n3. Display employees who are not working in the department of KING.\n4. Find employees who earn more than the salary of BLAKE.\n5. Display employees hired after JONES.\n6. Find employees whose department number is the same as CLARK.",
            "solution": "CREATE TABLE departments23(\ndepartment_id NUMBER(4) PRIMARY KEY,\ndepartment_name VARCHAR2(30),\nmanager_id NUMBER(6),\nlocation_id NUMBER(4)\n);\n\nCREATE TABLE employees23(\nemployee_id NUMBER(6) PRIMARY KEY,\nfirst_name VARCHAR2(20),\nlast_name VARCHAR2(25),\nemail VARCHAR2(25),\nphone_number VARCHAR2(20),\nhire_date DATE,\njob_id VARCHAR2(10),\nsalary NUMBER(8,2),\ncommission_pct NUMBER(2,2),\nmanager_id NUMBER(6),\ndepartment_id NUMBER(4),\nFOREIGN KEY(department_id)\nREFERENCES departments23(department_id)\n);\n\nINSERT INTO departments23 VALUES(10,'Sales',201,101);\nINSERT INTO departments23 VALUES(20,'HR',202,102);\nINSERT INTO departments23 VALUES(30,'IT',203,103);\n\nINSERT INTO employees23 VALUES(101,'ALLEN','Patil','a@gmail.com','9999999999',SYSDATE,'CLERK',30000,0.1,201,10);\nINSERT INTO employees23 VALUES(102,'MARTIN','Kale','m@gmail.com','8888888888',SYSDATE,'MANAGER',50000,0.2,202,20);\nINSERT INTO employees23 VALUES(103,'KING','Shah','k@gmail.com','7777777777',SYSDATE,'DEV',70000,0.1,203,30);\nINSERT INTO employees23 VALUES(104,'BLAKE','More','b@gmail.com','6666666666',SYSDATE,'MANAGER',45000,0.1,202,20);\nINSERT INTO employees23 VALUES(105,'CLARK','Patil','c@gmail.com','5555555555',SYSDATE,'CLERK',35000,0.2,201,10);\nINSERT INTO employees23 VALUES(106,'JONES','Kadam','j@gmail.com','4444444444',SYSDATE-10,'SALE',40000,0.1,203,30);\n\nSELECT *\nFROM employees23\nWHERE salary>(\nSELECT salary\nFROM employees23\nWHERE first_name='ALLEN'\n);\n\nSELECT *\nFROM employees23\nWHERE job_id=(\nSELECT job_id\nFROM employees23\nWHERE first_name='MARTIN'\n);\n\nSELECT *\nFROM employees23\nWHERE department_id<>(\nSELECT department_id\nFROM employees23\nWHERE first_name='KING'\n);\n\nSELECT *\nFROM employees23\nWHERE salary>(\nSELECT salary\nFROM employees23\nWHERE first_name='BLAKE'\n);\n\nSELECT *\nFROM employees23\nWHERE hire_date>(\nSELECT hire_date\nFROM employees23\nWHERE first_name='JONES'\n);\n\nSELECT *\nFROM employees23\nWHERE department_id=(\nSELECT department_id\nFROM employees23\nWHERE first_name='CLARK'\n);"
        },
        {
            "setName": "Set 24",
            "question": "Create below tables employee and department, insert 5 records each and solve the following queries\nEmployees (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)\nDepartments (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID)\n1. Find employees whose salary is greater than ANY employee in department 30.\n2. Display employees whose salary is greater than ALL employees in department 20.\n3. List employees working in departments where the job is MANAGER.\n4. Find employees whose salary is greater than the average salary of their own department.\n5. Display employees who earn the highest salary in their department.\n6. Find employees who have the same job as at least one employee in department 20.",
            "solution": "CREATE TABLE departments24(\ndepartment_id NUMBER(4) PRIMARY KEY,\ndepartment_name VARCHAR2(30),\nmanager_id NUMBER(6),\nlocation_id NUMBER(4)\n);\n\nCREATE TABLE employees24(\nemployee_id NUMBER(6) PRIMARY KEY,\nfirst_name VARCHAR2(20),\nlast_name VARCHAR2(25),\nemail VARCHAR2(25),\nphone_number VARCHAR2(20),\nhire_date DATE,\njob_id VARCHAR2(10),\nsalary NUMBER(8,2),\ncommission_pct NUMBER(2,2),\nmanager_id NUMBER(6),\ndepartment_id NUMBER(4),\nFOREIGN KEY(department_id)\nREFERENCES departments24(department_id)\n);\n\nINSERT INTO departments24 VALUES(10,'Sales',201,101);\nINSERT INTO departments24 VALUES(20,'HR',202,102);\nINSERT INTO departments24 VALUES(30,'IT',203,103);\n\nINSERT INTO employees24 VALUES(101,'Amit','Patil','a@gmail.com','9999999999',SYSDATE,'CLERK',30000,0.1,201,10);\nINSERT INTO employees24 VALUES(102,'Rohit','Kale','r@gmail.com','8888888888',SYSDATE,'MANAGER',50000,0.2,202,20);\nINSERT INTO employees24 VALUES(103,'Sneha','Shah','s@gmail.com','7777777777',SYSDATE,'DEV',70000,0.1,203,30);\nINSERT INTO employees24 VALUES(104,'Karan','More','k@gmail.com','6666666666',SYSDATE,'MANAGER',45000,0.1,202,20);\nINSERT INTO employees24 VALUES(105,'Priya','Patil','p@gmail.com','5555555555',SYSDATE,'CLERK',35000,0.2,201,10);\n\nSELECT *\nFROM employees24\nWHERE salary>ANY(\nSELECT salary\nFROM employees24\nWHERE department_id=30\n);\n\nSELECT *\nFROM employees24\nWHERE salary>ALL(\nSELECT salary\nFROM employees24\nWHERE department_id=20\n);\n\nSELECT *\nFROM employees24\nWHERE department_id IN(\nSELECT department_id\nFROM employees24\nWHERE job_id='MANAGER'\n);\n\nSELECT *\nFROM employees24 e\nWHERE salary>(\nSELECT AVG(salary)\nFROM employees24\nWHERE department_id=e.department_id\n);\n\nSELECT *\nFROM employees24 e\nWHERE salary=(\nSELECT MAX(salary)\nFROM employees24\nWHERE department_id=e.department_id\n);\n\nSELECT *\nFROM employees24\nWHERE job_id IN(\nSELECT job_id\nFROM employees24\nWHERE department_id=20\n);"
        },
        {
            "setName": "Set 32",
            "question": "Emp(emp_id,ename, street, city)\nworks(emp_id,c_id,ename, cname, sal)\nCompany(c_id,cname, city)\nManager(mgr_id, mgrname)\ni. Modify the database so that a particular company (eg. ABC) now in Pune\nii. Give all managers of Mbank a 10% raise. If salary is >20,000, give only 3% raise.\niii. Find out the names of all the employees who works in 'Bosch' company in city Pune\niv. Delete all records in the works table for employees of a particular company (Eg, SBC Company) whose salary>50,000.",
            "solution": "CREATE TABLE Emp(\nemp_id NUMBER PRIMARY KEY,\nename VARCHAR2(30),\nstreet VARCHAR2(30),\ncity VARCHAR2(30)\n);\n\nCREATE TABLE Company(\nc_id NUMBER PRIMARY KEY,\ncname VARCHAR2(30),\ncity VARCHAR2(30)\n);\n\nCREATE TABLE works(\nemp_id NUMBER,\nc_id NUMBER,\nename VARCHAR2(30),\ncname VARCHAR2(30),\nsal NUMBER,\nFOREIGN KEY(emp_id) REFERENCES Emp(emp_id),\nFOREIGN KEY(c_id) REFERENCES Company(c_id)\n);\n\nCREATE TABLE Manager(\nmgr_id NUMBER PRIMARY KEY,\nmgrname VARCHAR2(30)\n);\n\nINSERT INTO Emp VALUES(1,'Amit','JM Road','Pune');\nINSERT INTO Emp VALUES(2,'Rohit','FC Road','Mumbai');\nINSERT INTO Emp VALUES(3,'Sneha','MG Road','Pune');\nINSERT INTO Emp VALUES(4,'Priya','BTM','Bangalore');\nINSERT INTO Emp VALUES(5,'Karan','Ring Road','Delhi');\n\nINSERT INTO Company VALUES(101,'ABC','Mumbai');\nINSERT INTO Company VALUES(102,'Mbank','Pune');\nINSERT INTO Company VALUES(103,'Bosch','Pune');\nINSERT INTO Company VALUES(104,'SBC Company','Delhi');\n\nINSERT INTO works VALUES(1,101,'Amit','ABC',30000);\nINSERT INTO works VALUES(2,102,'Rohit','Mbank',25000);\nINSERT INTO works VALUES(3,103,'Sneha','Bosch',40000);\nINSERT INTO works VALUES(4,104,'Priya','SBC Company',60000);\nINSERT INTO works VALUES(5,103,'Karan','Bosch',45000);\n\nINSERT INTO Manager VALUES(201,'Raj');\nINSERT INTO Manager VALUES(202,'Neha');\n\nUPDATE Company\nSET city='Pune'\nWHERE cname='ABC';\n\nUPDATE works\nSET sal=sal+(sal*0.03)\nWHERE cname='Mbank'\nAND sal>20000;\n\nUPDATE works\nSET sal=sal+(sal*0.10)\nWHERE cname='Mbank'\nAND sal<=20000;\n\nSELECT e.ename\nFROM Emp e\nJOIN works w\nON e.emp_id=w.emp_id\nWHERE w.cname='Bosch'\nAND e.city='Pune';\n\nDELETE FROM works\nWHERE cname='SBC Company'\nAND sal>50000;"
        },
        {
            "setName": "Set 34",
            "question": "Employee(employee_name,street,city)\nWorks(employee_name,company_name,salary)\nCompany(company_name,city)\nManages(employee_name,manager_name)\n1. Find the names of employees who work for First Bank Coorporation.\n2. Find the names and cities of residence of all employees who work for First Bank Coorporation\n3. Find the names, street addresses, and cities of residence of all employees who work for First Bank Coorporation and earn more than $10000.\n4.Find all employees in the database who lives in the same cities as tha companies for which they work.\n5.Find all employees in the database who lives in the same cities and on the same streets as do their manager.\n6.Find all employees in the database who do not work for First Bank Coorporation\n7.Give all employees of First Bank Coorporation a 10% raise\n8.Delete all tuples in the \"Works\" relation for employees of \"Small Bank Coorporation\".",
            "solution": "CREATE TABLE Employee34(\nemployee_name VARCHAR2(30),\nstreet VARCHAR2(30),\ncity VARCHAR2(30)\n);\n\nCREATE TABLE Company34(\ncompany_name VARCHAR2(30),\ncity VARCHAR2(30)\n);\n\nCREATE TABLE Works34(\nemployee_name VARCHAR2(30),\ncompany_name VARCHAR2(30),\nsalary NUMBER\n);\n\nCREATE TABLE Manages34(\nemployee_name VARCHAR2(30),\nmanager_name VARCHAR2(30)\n);\n\nINSERT INTO Employee34 VALUES('Amit','JM Road','Pune');\nINSERT INTO Employee34 VALUES('Rohit','FC Road','Mumbai');\nINSERT INTO Employee34 VALUES('Sneha','MG Road','Pune');\nINSERT INTO Employee34 VALUES('Priya','BTM','Bangalore');\nINSERT INTO Employee34 VALUES('Jones','Ring Road','Delhi');\n\nINSERT INTO Company34 VALUES('First Bank Corporation','Pune');\nINSERT INTO Company34 VALUES('Small Bank Corporation','Mumbai');\nINSERT INTO Company34 VALUES('ABC Corp','Delhi');\n\nINSERT INTO Works34 VALUES('Amit','First Bank Corporation',15000);\nINSERT INTO Works34 VALUES('Rohit','Small Bank Corporation',12000);\nINSERT INTO Works34 VALUES('Sneha','First Bank Corporation',18000);\nINSERT INTO Works34 VALUES('Priya','ABC Corp',9000);\nINSERT INTO Works34 VALUES('Jones','First Bank Corporation',25000);\n\nINSERT INTO Manages34 VALUES('Amit','Rohit');\nINSERT INTO Manages34 VALUES('Sneha','Jones');\nINSERT INTO Manages34 VALUES('Priya','Rohit');\n\nSELECT employee_name\nFROM Works34\nWHERE company_name='First Bank Corporation';\n\nSELECT e.employee_name,e.city\nFROM Employee34 e\nJOIN Works34 w\nON e.employee_name=w.employee_name\nWHERE w.company_name='First Bank Corporation';\n\nSELECT e.employee_name,e.street,e.city\nFROM Employee34 e\nJOIN Works34 w\nON e.employee_name=w.employee_name\nWHERE w.company_name='First Bank Corporation'\nAND w.salary>10000;\n\nSELECT e.employee_name\nFROM Employee34 e\nJOIN Works34 w\nON e.employee_name=w.employee_name\nJOIN Company34 c\nON w.company_name=c.company_name\nWHERE e.city=c.city;\n\nSELECT e.employee_name\nFROM Employee34 e\nJOIN Manages34 m\nON e.employee_name=m.employee_name\nJOIN Employee34 mgr\nON m.manager_name=mgr.employee_name\nWHERE e.city=mgr.city\nAND e.street=mgr.street;\n\nSELECT employee_name\nFROM Works34\nWHERE company_name<>'First Bank Corporation';\n\nUPDATE Works34\nSET salary=salary+(salary*0.10)\nWHERE company_name='First Bank Corporation';\n\nDELETE FROM Works34\nWHERE company_name='Small Bank Corporation';"
        },
        {
            "setName": "Set 35",
            "question": "Employee(employee_name,street,city)\nWorks(employee_name,company_name,salary)\nCompany(company_name,city)\nManages(employee_name,manager_name)\n1) Find all employees in the database who earn more than each employee of Small Bank Coorporation\n2) Assume that the company is may be located in several cities. Find all companies located in every city in which Small Bank Coorporation is located.\n3) Find all employees who earn more than the average salary of all employees of their companies.\n4) Find the company that has the most employees.\n5) Find the company that has the smallest payroll.\n6) Find those companies whose employees earn a higher salary, on average, than the average salary at First Bank Coorporation.\n7) Modify the database so that \"Jones\" now lives in Newtown.",
            "solution": "CREATE TABLE Employee35(\nemployee_name VARCHAR2(30),\nstreet VARCHAR2(30),\ncity VARCHAR2(30)\n);\n\nCREATE TABLE Company35(\ncompany_name VARCHAR2(30),\ncity VARCHAR2(30)\n);\n\nCREATE TABLE Works35(\nemployee_name VARCHAR2(30),\ncompany_name VARCHAR2(30),\nsalary NUMBER\n);\n\nCREATE TABLE Manages35(\nemployee_name VARCHAR2(30),\nmanager_name VARCHAR2(30)\n);\n\nINSERT INTO Employee35 VALUES('Amit','JM Road','Pune');\nINSERT INTO Employee35 VALUES('Rohit','FC Road','Mumbai');\nINSERT INTO Employee35 VALUES('Sneha','MG Road','Pune');\nINSERT INTO Employee35 VALUES('Priya','BTM','Bangalore');\nINSERT INTO Employee35 VALUES('Jones','Ring Road','Delhi');\n\nINSERT INTO Company35 VALUES('First Bank Corporation','Pune');\nINSERT INTO Company35 VALUES('Small Bank Corporation','Mumbai');\nINSERT INTO Company35 VALUES('ABC Corp','Delhi');\n\nINSERT INTO Works35 VALUES('Amit','First Bank Corporation',15000);\nINSERT INTO Works35 VALUES('Rohit','Small Bank Corporation',12000);\nINSERT INTO Works35 VALUES('Sneha','First Bank Corporation',18000);\nINSERT INTO Works35 VALUES('Priya','ABC Corp',9000);\nINSERT INTO Works35 VALUES('Jones','First Bank Corporation',25000);\n\nINSERT INTO Manages35 VALUES('Amit','Rohit');\nINSERT INTO Manages35 VALUES('Sneha','Jones');\nINSERT INTO Manages35 VALUES('Priya','Rohit');\n\nSELECT employee_name\nFROM Works35\nWHERE salary>ALL(\nSELECT salary\nFROM Works35\nWHERE company_name='Small Bank Corporation'\n);\n\nSELECT DISTINCT c1.company_name\nFROM Company35 c1\nWHERE NOT EXISTS(\nSELECT city\nFROM Company35\nWHERE company_name='Small Bank Corporation'\nMINUS\nSELECT city\nFROM Company35 c2\nWHERE c1.company_name=c2.company_name\n);\n\nSELECT employee_name\nFROM Works35 w1\nWHERE salary>(\nSELECT AVG(salary)\nFROM Works35 w2\nWHERE w1.company_name=w2.company_name\n);\n\nSELECT company_name\nFROM Works35\nGROUP BY company_name\nHAVING COUNT(*)=(\nSELECT MAX(COUNT(*))\nFROM Works35\nGROUP BY company_name\n);\n\nSELECT company_name\nFROM Works35\nGROUP BY company_name\nHAVING SUM(salary)=(\nSELECT MIN(SUM(salary))\nFROM Works35\nGROUP BY company_name\n);\n\nSELECT company_name\nFROM Works35\nGROUP BY company_name\nHAVING AVG(salary)>(\nSELECT AVG(salary)\nFROM Works35\nWHERE company_name='First Bank Corporation'\n);\n\nUPDATE Employee35\nSET city='Newtown'\nWHERE employee_name='Jones';"
        }
    ],
    "plsql": [
        {
            "setName": "Set 15",
            "question": "Write a program that will prompt for a EMPNO,ENAME,SAL.If EMPNO does not exists in EMP table then\nINSERT the EMPNO,ENAME,SAL into the EMP table else UPDATE NAME,SAL for that EMPNO.",
            "solution": "ACCEPT p_empno NUMBER PROMPT 'Enter EMPNO : '\nACCEPT p_ename CHAR PROMPT 'Enter ENAME : '\nACCEPT p_sal NUMBER PROMPT 'Enter SALARY : '\n\nDECLARE\nv_count NUMBER;\nBEGIN\nSELECT COUNT(*)\nINTO v_count\nFROM emp\nWHERE empno=&p_empno;\n\nIF v_count=0 THEN\nINSERT INTO emp(empno,ename,sal)\nVALUES(&p_empno,'&p_ename',&p_sal);\n\nDBMS_OUTPUT.PUT_LINE('Record Inserted');\nELSE\nUPDATE emp\nSET ename='&p_ename',\nsal=&p_sal\nWHERE empno=&p_empno;\n\nDBMS_OUTPUT.PUT_LINE('Record Updated');\nEND IF;\nEND;\n/"
        },
        {
            "setName": "Set 16",
            "question": "Write a program that will prompt for number and display whether the number is ODD or EVEN\nnumber.Add user defined exception to check the number is negative.",
            "solution": "ACCEPT num NUMBER PROMPT 'Enter Number : '\n\nDECLARE\nn NUMBER:=&num;\nnegative_number EXCEPTION;\nBEGIN\nIF n<0 THEN\nRAISE negative_number;\nELSIF MOD(n,2)=0 THEN\nDBMS_OUTPUT.PUT_LINE('EVEN NUMBER');\nELSE\nDBMS_OUTPUT.PUT_LINE('ODD NUMBER');\nEND IF;\n\nEXCEPTION\nWHEN negative_number THEN\nDBMS_OUTPUT.PUT_LINE('NEGATIVE NUMBER NOT ALLOWED');\nEND;\n/"
        },
        {
            "setName": "Set 17",
            "question": "Write program that prompts for EMPNO and update his salary based on the below specification:\nIf the employee belongs to DEPTNO 10 then update his salary by 10%.\nIf the employee belongs to DEPTNO 20 then update his salary by 15%.\nIf the employee belongs to other DEPTNO then update his salary with SALARY+COMM.",
            "solution": "ACCEPT p_empno NUMBER PROMPT 'Enter EMPNO : '\n\nDECLARE\nv_deptno NUMBER;\nBEGIN\nSELECT deptno\nINTO v_deptno\nFROM emp\nWHERE empno=&p_empno;\n\nIF v_deptno=10 THEN\nUPDATE emp\nSET sal=sal+(sal*0.10)\nWHERE empno=&p_empno;\n\nELSIF v_deptno=20 THEN\nUPDATE emp\nSET sal=sal+(sal*0.15)\nWHERE empno=&p_empno;\n\nELSE\nUPDATE emp\nSET sal=sal+comm\nWHERE empno=&p_empno;\nEND IF;\n\nDBMS_OUTPUT.PUT_LINE('Salary Updated');\nEND;\n/"
        },
        {
            "setName": "Set 18",
            "question": "Unnamed PL/SQL code block: Use of Control structure and Exception handling is mandatory. Write a PL/SQL block of code for the following requirements:-Consider table Stud(Roll, Att,Status) Write a PL/SQL block for following requirement and handle the exceptions. Roll no. of student will be entered by user. Attendance of roll no. entered by user will be checked in Stud table. If attendance is less than 75% then display the message \"Term not granted\" and set the status in stud table as \"D\". Otherwise display message \"Term granted\" and set the status in stud table as \"ND\"",
            "solution": "CREATE TABLE Stud(\nroll NUMBER PRIMARY KEY,\natt NUMBER,\nstatus VARCHAR2(10)\n);\n\nINSERT INTO Stud VALUES(1,80,NULL);\nINSERT INTO Stud VALUES(2,60,NULL);\nINSERT INTO Stud VALUES(3,75,NULL);\n\nACCEPT rno NUMBER PROMPT 'Enter Roll Number : '\n\nDECLARE\nv_att NUMBER;\nBEGIN\nSELECT att\nINTO v_att\nFROM Stud\nWHERE roll=&rno;\n\nIF v_att<75 THEN\nUPDATE Stud\nSET status='D'\nWHERE roll=&rno;\n\nDBMS_OUTPUT.PUT_LINE('Term not granted');\nELSE\nUPDATE Stud\nSET status='ND'\nWHERE roll=&rno;\n\nDBMS_OUTPUT.PUT_LINE('Term granted');\nEND IF;\n\nEXCEPTION\nWHEN NO_DATA_FOUND THEN\nDBMS_OUTPUT.PUT_LINE('Student Not Found');\nEND;\n/"
        },
        {
            "setName": "Set 19",
            "question": "Unnamed PL/SQL code block: Use of Control structure and Exception handling is mandatory.\nWrite a PL/SQL block of code for the following requirements:-\nSchema:\n1. Borrower(Rollin, Name, DateofIssue, NameofBook, Status)\n2. Fine(Roll_no,Date,Amt)\nAccept roll_no & name of book from user.\nCheck the number of days (from date of issue), if days are between 15 to 30 then fine amount will be Rs 5per day.\nIf no. of days>30, per day fine will be Rs 50 per day & for days less than 30, Rs. 5 per day.\nAfter submitting the book, status will change from I to R.\nIf condition of fine is true, then details will be stored into fine table.",
            "solution": "CREATE TABLE Borrower(\nrollin NUMBER,\nname VARCHAR2(30),\ndateofissue DATE,\nnameofbook VARCHAR2(30),\nstatus VARCHAR2(5)\n);\n\nCREATE TABLE Fine(\nroll_no NUMBER,\nfdate DATE,\namt NUMBER\n);\n\nINSERT INTO Borrower\nVALUES(1,'Amit',SYSDATE-20,'DBMS','I');\n\nINSERT INTO Borrower\nVALUES(2,'Rohit',SYSDATE-40,'CN','I');\n\nACCEPT rno NUMBER PROMPT 'Enter Roll Number : '\nACCEPT bname CHAR PROMPT 'Enter Book Name : '\n\nDECLARE\nv_days NUMBER;\nv_fine NUMBER;\nBEGIN\nSELECT TRUNC(SYSDATE-dateofissue)\nINTO v_days\nFROM Borrower\nWHERE rollin=&rno\nAND nameofbook='&bname';\n\nIF v_days BETWEEN 15 AND 30 THEN\nv_fine:=v_days*5;\n\nELSIF v_days>30 THEN\nv_fine:=v_days*50;\n\nELSE\nv_fine:=0;\nEND IF;\n\nUPDATE Borrower\nSET status='R'\nWHERE rollin=&rno\nAND nameofbook='&bname';\n\nIF v_fine>0 THEN\nINSERT INTO Fine\nVALUES(&rno,SYSDATE,v_fine);\nEND IF;\n\nDBMS_OUTPUT.PUT_LINE('Fine Amount = '||v_fine);\n\nEXCEPTION\nWHEN NO_DATA_FOUND THEN\nDBMS_OUTPUT.PUT_LINE('Record Not Found');\nEND;\n/"
        },
        {
            "setName": "Set 21",
            "question": "Write a program that displays the Top N salaries using simple Explicit Cursors.",
            "solution": "DECLARE\nCURSOR c1 IS\nSELECT ename,sal\nFROM emp\nORDER BY sal DESC;\n\nv_ename emp.ename%TYPE;\nv_sal emp.sal%TYPE;\nn NUMBER:=5;\ni NUMBER:=0;\n\nBEGIN\nOPEN c1;\n\nLOOP\nFETCH c1 INTO v_ename,v_sal;\n\nEXIT WHEN c1%NOTFOUND OR i=n;\n\nDBMS_OUTPUT.PUT_LINE(v_ename||' '||v_sal);\n\ni:=i+1;\nEND LOOP;\n\nCLOSE c1;\nEND;\n/"
        },
        {
            "setName": "Set 22",
            "question": "PL/SQL Stored Procedure.\nWrite a Stored Procedure namely proc_Grade for the categorization of student. If marks scored by students in examination is <=1500 and marks>=990 then student will be placed in distinction category if marks scored are between 989 and900 category is first class, if marks 899 and 825 category is Higher Second Class\nWrite a PL/SQL block for using procedure created with above requirement. Stud_Marks(name, total_marks) Result(Roll,Name, Class).",
            "solution": "CREATE TABLE Stud_Marks(\nroll NUMBER,\nname VARCHAR2(30),\ntotal_marks NUMBER\n);\n\nCREATE TABLE Result(\nroll NUMBER,\nname VARCHAR2(30),\nclass VARCHAR2(30)\n);\n\nINSERT INTO Stud_Marks VALUES(1,'Amit',1200);\nINSERT INTO Stud_Marks VALUES(2,'Rohit',950);\nINSERT INTO Stud_Marks VALUES(3,'Sneha',850);\n\nCREATE OR REPLACE PROCEDURE proc_grade(\np_roll NUMBER,\np_name VARCHAR2,\np_marks NUMBER\n)\nIS\nv_class VARCHAR2(30);\nBEGIN\n\nIF p_marks<=1500 AND p_marks>=990 THEN\nv_class:='Distinction';\n\nELSIF p_marks BETWEEN 900 AND 989 THEN\nv_class:='First Class';\n\nELSIF p_marks BETWEEN 825 AND 899 THEN\nv_class:='Higher Second Class';\n\nELSE\nv_class:='Fail';\nEND IF;\n\nINSERT INTO Result\nVALUES(p_roll,p_name,v_class);\n\nEND;\n/\n\nBEGIN\nproc_grade(1,'Amit',1200);\nproc_grade(2,'Rohit',950);\nproc_grade(3,'Sneha',850);\nEND;\n/\n\nSELECT * FROM Result;"
        },
        {
            "setName": "Set 25",
            "question": "Write a database trigger on Library table. The System should keep track of the records that are being updated or deleted. The old value of updated or deleted records should be added in Library_ Audit table. Frame the problem statement for writing Database Triggers of all types, in-line with above statement. The problem statement should clearly state the requirements.",
            "solution": "CREATE TABLE Library(\nbook_id NUMBER,\nbook_name VARCHAR2(30),\nauthor VARCHAR2(30),\nprice NUMBER\n);\n\nCREATE TABLE Library_Audit(\nbook_id NUMBER,\nbook_name VARCHAR2(30),\nauthor VARCHAR2(30),\nprice NUMBER,\naction_type VARCHAR2(20),\naction_date DATE\n);\n\nINSERT INTO Library\nVALUES(1,'DBMS','Korth',500);\n\nINSERT INTO Library\nVALUES(2,'CN','Tanenbaum',600);\n\nCREATE OR REPLACE TRIGGER trg_library_audit\nBEFORE UPDATE OR DELETE\nON Library\nFOR EACH ROW\nBEGIN\n\nINSERT INTO Library_Audit\nVALUES(\n:OLD.book_id,\n:OLD.book_name,\n:OLD.author,\n:OLD.price,\nCASE\nWHEN UPDATING THEN 'UPDATE'\nWHEN DELETING THEN 'DELETE'\nEND,\nSYSDATE\n);\n\nEND;\n/\n\nUPDATE Library\nSET price=700\nWHERE book_id=1;\n\nDELETE FROM Library\nWHERE book_id=2;\n\nSELECT * FROM Library_Audit;"
        }
    ],
    "mongodb": [
        {
            "setName": "Set 26",
            "question": "Collection \"orderinfo\" which contains the documents given as below\n{\ncust_id:123\ncust_name:\"abc\",\nstatus:\"A\",\nprice:250\n}\n1) find the average price for each customers having status 'A'\n2) Display the status of the customers whose amount/price lie between 100 and 1000\n3) Display the customers information without \"_id\" .\n4) create a simple index on onderinfo collection and fire the queries.",
            "solution": "use orderdb\n\ndb.orderinfo.insertMany([\n{\ncust_id:123,\ncust_name:\"abc\",\nstatus:\"A\",\nprice:250\n},\n{\ncust_id:124,\ncust_name:\"xyz\",\nstatus:\"A\",\nprice:500\n},\n{\ncust_id:125,\ncust_name:\"pqr\",\nstatus:\"B\",\nprice:700\n},\n{\ncust_id:126,\ncust_name:\"lmn\",\nstatus:\"A\",\nprice:900\n}\n])\n\ndb.orderinfo.aggregate([\n{\n$match:{status:\"A\"}\n},\n{\n$group:{\n_id:\"$cust_name\",\navg_price:{$avg:\"$price\"}\n}\n}\n])\n\ndb.orderinfo.find(\n{\nprice:{$gte:100,$lte:1000}\n},\n{\nstatus:1,\n_id:0\n}\n)\n\ndb.orderinfo.find(\n{},\n{\n_id:0\n}\n)\n\ndb.orderinfo.createIndex({cust_name:1})\n\ndb.orderinfo.find({cust_name:\"abc\"})"
        },
        {
            "setName": "Set 27",
            "question": "Collection \"movies\" which contains the documents given as below(Perform on Mongo Terminal)\n{\nname: \"Movie1\",\ntype: \"action\",\nbudget:1000000\nproducer:{\nname: \"producer1\",\naddress:\"PUNE\"\n}\n}\ni. Find the name of the movie having budget greater than 1,00,000.\nii. Find the name of producer who lives in Pune\niii. Update the type of movie \"action\" to \"horror\"\niv. Find all the documents produced by name \"producer1\" with their address",
            "solution": "use moviedb\n\ndb.movies.insertMany([\n{\nname:\"Movie1\",\ntype:\"action\",\nbudget:1000000,\nproducer:{\nname:\"producer1\",\naddress:\"PUNE\"\n}\n},\n{\nname:\"Movie2\",\ntype:\"comedy\",\nbudget:500000,\nproducer:{\nname:\"producer2\",\naddress:\"MUMBAI\"\n}\n}\n])\n\ndb.movies.find(\n{\nbudget:{$gt:100000}\n},\n{\nname:1,\n_id:0\n}\n)\n\ndb.movies.find(\n{\n\"producer.address\":\"PUNE\"\n},\n{\n\"producer.name\":1,\n_id:0\n}\n)\n\ndb.movies.updateMany(\n{\ntype:\"action\"\n},\n{\n$set:{type:\"horror\"}\n}\n)\n\ndb.movies.find(\n{\n\"producer.name\":\"producer1\"\n},\n{\nname:1,\n\"producer.address\":1,\n_id:0\n}\n)"
        },
        {
            "setName": "Set 28",
            "question": "Consider following structure for Mongodb collection and write a query for following requirements in Mongodb\nTeachers (Tname,dno,Experience,Salary,Date_of_Joining)\nDepartment (Dno,Dname)\nStudents(Sname,Roll_No,Class)\n1. Write a query to create above collection insert some sample documents.\n2. Find the information about all teachers of Dno=2 and having salary greater than or equal to 10,000/-\n3. Find the student information having Roll_no=2 or Sname='xyz'\n4. Update student name whose Roll_No=5\n5. Delete all student whose Class is 'FE'\n6. Apply index on Students Collection",
            "solution": "use college\n\ndb.Teachers.insertMany([\n{\nTname:\"Amit\",\ndno:1,\nExperience:5,\nSalary:15000,\nDate_of_Joining:new Date(\"2020-01-10\")\n},\n{\nTname:\"Rohit\",\ndno:2,\nExperience:3,\nSalary:12000,\nDate_of_Joining:new Date(\"2021-06-15\")\n},\n{\nTname:\"Sneha\",\ndno:2,\nExperience:6,\nSalary:18000,\nDate_of_Joining:new Date(\"2019-03-20\")\n}\n])\n\ndb.Department.insertMany([\n{\nDno:1,\nDname:\"Computer\"\n},\n{\nDno:2,\nDname:\"IT\"\n}\n])\n\ndb.Students.insertMany([\n{\nSname:\"Amit\",\nRoll_No:1,\nClass:\"FE\"\n},\n{\nSname:\"xyz\",\nRoll_No:2,\nClass:\"SE\"\n},\n{\nSname:\"Rohit\",\nRoll_No:5,\nClass:\"FE\"\n}\n])\n\ndb.Teachers.find(\n{\ndno:2,\nSalary:{$gte:10000}\n}\n)\n\ndb.Students.find(\n{\n$or:[\n{Roll_No:2},\n{Sname:\"xyz\"}\n]\n}\n)\n\ndb.Students.updateOne(\n{\nRoll_No:5\n},\n{\n$set:{Sname:\"Neha\"}\n}\n)\n\ndb.Students.deleteMany(\n{\nClass:\"FE\"\n}\n)\n\ndb.Students.createIndex({Roll_No:1})"
        },
        {
            "setName": "Set 29",
            "question": "Perform aggregation and Indexing using mongodb on below database\n1. Create a database department\n2. Create a collection as teacher with fields as name , department ,experience and salary\n3. Display the department wise average salary.\n4. Display the no. Of employees working in each department.\n5. Display the department wise minimum salary.\n6. Apply index and drop index",
            "solution": "use department\n\ndb.teacher.insertMany([\n{\nname:\"Amit\",\ndepartment:\"IT\",\nexperience:5,\nsalary:50000\n},\n{\nname:\"Rohit\",\ndepartment:\"HR\",\nexperience:3,\nsalary:40000\n},\n{\nname:\"Sneha\",\ndepartment:\"IT\",\nexperience:6,\nsalary:60000\n},\n{\nname:\"Priya\",\ndepartment:\"Sales\",\nexperience:4,\nsalary:45000\n}\n])\n\ndb.teacher.aggregate([\n{\n$group:{\n_id:\"$department\",\navg_salary:{$avg:\"$salary\"}\n}\n}\n])\n\ndb.teacher.aggregate([\n{\n$group:{\n_id:\"$department\",\nemployee_count:{$sum:1}\n}\n}\n])\n\ndb.teacher.aggregate([\n{\n$group:{\n_id:\"$department\",\nmin_salary:{$min:\"$salary\"}\n}\n}\n])\n\ndb.teacher.createIndex({department:1})\n\ndb.teacher.dropIndex({department:1})"
        },
        {
            "setName": "Set 30",
            "question": "1. Create database product_detail\n2. Show Database\n3. Create collection product\n4. Show collection\n5. Insert below documents\n{\"item\": \"pen\", \"price\": 10, \"quantity\": 2}{\"item\": \"book\", \"price\": 50, \"quantity\": 1}{\"item\": \"pen\", \"price\": 10, \"quantity\": 5}{\"item\": \"pencil\", \"price\": 5, \"quantity\": 10}\n6. Retrieve documents from collection.\n7. Create index on item in ascending order\n8. Show index\n9. Create index on price in ascending and quantity as descending\n10. Drop index on price",
            "solution": "use product_detail\n\nshow dbs\n\ndb.createCollection(\"product\")\n\nshow collections\n\ndb.product.insertMany([\n{\"item\":\"pen\",\"price\":10,\"quantity\":2},\n{\"item\":\"book\",\"price\":50,\"quantity\":1},\n{\"item\":\"pen\",\"price\":10,\"quantity\":5},\n{\"item\":\"pencil\",\"price\":5,\"quantity\":10}\n])\n\ndb.product.find()\n\ndb.product.createIndex({item:1})\n\ndb.product.getIndexes()\n\ndb.product.createIndex({price:1,quantity:-1})\n\ndb.product.dropIndex({price:1,quantity:-1})"
        },
        {
            "setName": "Set 31",
            "question": "Collection \"orderinfo\" which contains the documents given as below\n{\ncust_id:123\ncust_name:\"abc\",\nstatus:\"A\",\nprice:250\n}\ni. Display the name of the customer having the price between 250 and 450\nii. Increment the price by 10 for cust_id: 123 and decrement the price by 5 for cust_id: 124\niii. Remove any one of the field from the orderinfo collection.\niv. Find the name of the customer whose status is either A or price is 250 or both.",
            "solution": "use orderdb\n\ndb.orderinfo.insertMany([\n{\ncust_id:123,\ncust_name:\"abc\",\nstatus:\"A\",\nprice:250\n},\n{\ncust_id:124,\ncust_name:\"xyz\",\nstatus:\"B\",\nprice:400\n},\n{\ncust_id:125,\ncust_name:\"pqr\",\nstatus:\"A\",\nprice:500\n}\n])\n\ndb.orderinfo.find(\n{\nprice:{$gte:250,$lte:450}\n},\n{\ncust_name:1,\n_id:0\n}\n)\n\ndb.orderinfo.updateOne(\n{\ncust_id:123\n},\n{\n$inc:{price:10}\n}\n)\n\ndb.orderinfo.updateOne(\n{\ncust_id:124\n},\n{\n$inc:{price:-5}\n}\n)\n\ndb.orderinfo.updateOne(\n{},\n{\n$unset:{status:\"\"}\n}\n)\n\ndb.orderinfo.find(\n{\n$or:[\n{status:\"A\"},\n{price:250}\n]\n},\n{\ncust_name:1,\n_id:0\n}\n)"
        },
        {
            "setName": "Set 33",
            "question": "1. Create database Employee.\n2.Create collection emp1 using createCollection method.\n3.Insert 4 to 5 documents in emp1 collection.(eno,ename,address,sal)\n4.display all documents.\n5.Display all employess having salary greater than 5000\n6.Display all employess having salary less than 15000\n7.Display all employess having salary greater than 10000 and less than 20000.\n8.Update sal of all employee with 10%\n9.Delete employee having salary less than 5000.\n10.Rename collection emp1 with employee1.\n11.Display employee whose name start with n.\n12.sort name in ascending order.\n13.Create a new database with name Employee1.\n14.Drop employee1 database.\n15.Create collection emp1 using insert method.\n16.Drop collection emp1.",
            "solution": "use Employee\n\ndb.createCollection(\"emp1\")\n\ndb.emp1.insertMany([\n{\neno:1,\nename:\"Amit\",\naddress:\"Pune\",\nsal:12000\n},\n{\neno:2,\nename:\"Neha\",\naddress:\"Mumbai\",\nsal:18000\n},\n{\neno:3,\nename:\"Rohit\",\naddress:\"Delhi\",\nsal:4000\n},\n{\neno:4,\nename:\"Nikhil\",\naddress:\"Pune\",\nsal:22000\n}\n])\n\ndb.emp1.find()\n\ndb.emp1.find(\n{\nsal:{$gt:5000}\n}\n)\n\ndb.emp1.find(\n{\nsal:{$lt:15000}\n}\n)\n\ndb.emp1.find(\n{\nsal:{$gt:10000,$lt:20000}\n}\n)\n\ndb.emp1.updateMany(\n{},\n{\n$mul:{sal:1.10}\n}\n)\n\ndb.emp1.deleteMany(\n{\nsal:{$lt:5000}\n}\n)\n\ndb.emp1.renameCollection(\"employee1\")\n\ndb.employee1.find(\n{\nename:/^n/i\n}\n)\n\ndb.employee1.find().sort({ename:1})\n\nuse Employee1\n\ndb.dropDatabase()\n\ndb.emp1.insertOne(\n{\neno:5,\nename:\"Karan\",\naddress:\"Nagpur\",\nsal:15000\n}\n)\n\ndb.emp1.drop()"
        }
    ]
};
